'''
    Test whether LLM could generate an optimized AIG program
    step 1. construct the init six AIG prompt: 
            a. collapse; sop; strash
            b. collapse; bdd; strash
            c. collapse; sop; strash; resub
            d. collapse; bdd; strash; resub
            e. collapse; sop; strash; resyn2
            f. collapse; bdd; strash; resyn2
    step 2. main Loop
            a. use prompt to generate several AIG prompts (EOH, E1-2, M1-3)
            b. legalize the AIG prompts.
            c. evalute the legalized AIG nodes
            c. updates the AIG prompt library (keep in twenty populations)
    step 3. output the best AIG prompt
'''

from eoh import eoh
from eoh.utils.getParas import Paras
import utils
import argparse
import os
import time
from torch.utils.tensorboard import SummaryWriter

# Parameter initilization 
if __name__ == '__main__':
        parser = argparse.ArgumentParser(description='runEoh4AIG')
        parser.add_argument('--truth_file_path', default='./example/circuit.truth', type=str)
        parser.add_argument('--ec_pop_size', default=3, type=int)
        parser.add_argument('--ec_n_pop', default=5, type=int)
        parser.add_argument('--ec_operators', default=['e1', 'm1'], nargs='+', type=str)
        parser.add_argument('--llm_model', default='gpt-3.5-turbo', type=str)
        parser.add_argument('--use_fx', action='store_true')
        parser.add_argument('--local_search', action='store_true')
        parser.add_argument('--random_generated', action='store_true')
        parser.add_argument('--sample_num', default=1, type=int)
        parser.add_argument('--shannon_decomposition', action='store_true')
        parser.add_argument('--prune', action='store_true') # whether to prune those bad solutions generated by random_generated
        parser.add_argument('--reflect', action='store_true')
        parser.add_argument('--LLM_generation_initial', action='store_true')
        parser.add_argument('--legalized_parent', action='store_true')
        args = parser.parse_args()
        input_number, output_number = utils.get_inout(args.truth_file_path)
        args.input_number = input_number
        args.output_number = output_number
        paras = Paras() 
        output_path = utils.create_output_path()
        utils.save_config(args, output_path)
        print(output_path)
        print(f'The input number is {input_number} and output_number is {output_number}')
        writer = SummaryWriter(log_dir=os.path.join(output_path, "runs"))
        # Set parameters 
        paras.set_paras(
                        truth_file_path= args.truth_file_path,
                        writer = writer,
                        use_fx = args.use_fx, 
                        local_search = args.local_search,
                        exp_debug_mode = False,
                        method = "aig",    # ['ael','eoh','aig]
                        problem = "AIG", #['tsp_construct','bp_online','AIG']
                        ec_operators = args.ec_operators,
                        random_generated = args.random_generated,
                        sample_num = args.sample_num,
                        shannon_decomposition = args.shannon_decomposition,
                        prune = args.prune,
                        reflect = args.reflect,
                        LLM_generation_initial = args.LLM_generation_initial,
                        legalized_parent = args.legalized_parent,
                        # ec_operators = ['m1', 'm2'],
                        # ec_operators = ['rewrite', 'resub'],
                        llm_api_endpoint = "provide_your_endpoint_here", # set your LLM endpoint
                        llm_api_key = "provide_your_endpoint_here",   # set your key
                        llm_model = args.llm_model,
                        exp_output_path = output_path,
                        ec_pop_size = args.ec_pop_size, # number of samples in each population
                        ec_n_pop = args.ec_n_pop,  # number of populations
                        exp_n_proc = 4  # multi-core parallel
                        )              
        # initilization
        evolution = eoh.EVOL(paras)

        # run 
        start_time = time.time()
        evolution.run()
        end_time = time.time()
        print(f'The all duration time is {end_time-start_time}')
